Repository linode/linode-blockstorage-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#394 [feat] enable forked repo PR to run GHA e2e workflow
  .github/workflows/ci.yml
Labels: new-feature

#382 Resize fs
  .golangci.yml
  Dockerfile
  Dockerfile.dev
  docs/deployment.md
  internal/driver/driver.go
  internal/driver/driver_test.go
  internal/driver/errors.go
  internal/driver/identityserver.go
  internal/driver/identityserver_test.go
  internal/driver/nodeserver.go
  internal/driver/nodeserver_all.go
  internal/driver/nodeserver_helpers.go
  internal/driver/nodeserver_helpers_linux_test.go
  internal/driver/nodeserver_helpers_test.go
  internal/driver/nodeserver_luks_encryption_test.go
  internal/driver/nodeserver_test.go
  main.go
  mocks/mock_safe-mounter.go
  pkg/linode-volumes/utils.go
  pkg/mount-manager/safe_mounter.go
  tests/e2e/test/pod-pvc-basic-filesystem/chainsaw-test.yaml
  tests/e2e/test/pod-pvc-create-ext4-filesystem/chainsaw-test.yaml
  tests/e2e/test/pod-pvc-create-xfs-filesystem/chainsaw-test.yaml
  tests/e2e/test/pod-pvc-expand-raw-block-storage/chainsaw-test.yaml
  tests/e2e/test/pod-pvc-expand-storage-size/chainsaw-test.yaml
  tests/e2e/test/pod-pvc-linode-encryption/chainsaw-test.yaml
  tests/e2e/test/pod-pvc-luks-mov-volume/chainsaw-test.yaml
  tests/e2e/test/pod-pvc-luks-remount/chainsaw-test.yaml
  tests/e2e/test/pod-pvc-luks/chainsaw-test.yaml
  tests/e2e/test/pod-pvc-readonly/chainsaw-test.yaml
  tests/e2e/test/statefulset-pvc/chainsaw-test.yaml
Labels: added-feature

#396 Update csi-attacher and increase attacher timeout
  deploy/kubernetes/base/ss-csi-linode-controller.yaml
  helm-chart/csi-driver/templates/csi-linode-controller.yaml
  helm-chart/csi-driver/values.yaml
  internal/driver/deploy/releases/linode-blockstorage-csi-driver.yaml
Labels: changed, improvement

#398 update PR labels
  .github/labels.yml
Labels: repo-ci-improvement

#392 Unpublish if no nodeid
  internal/driver/controllerserver.go
  internal/driver/controllerserver_helper.go
  internal/driver/controllerserver_test.go
  internal/driver/driver.go
  internal/driver/identityserver.go
  internal/driver/luks.go
  internal/driver/metadata.go
  internal/driver/nodeserver.go
  internal/driver/nodeserver_all.go
  internal/driver/nodeserver_helpers.go
  main.go
  pkg/logger/logger.go
  pkg/logger/logger_test.go
Labels: bugfix

#383 unexpected node reboot
  tests/e2e/test/pod-pvc-unexpected-reboot/assert-csi-driver-resources.yaml
  tests/e2e/test/pod-pvc-unexpected-reboot/assert-pod.yaml
  tests/e2e/test/pod-pvc-unexpected-reboot/assert-pvc-pod.yaml
  tests/e2e/test/pod-pvc-unexpected-reboot/chainsaw-test.yaml
  tests/e2e/test/pod-pvc-unexpected-reboot/create-pvc-pod.yaml
  tests/e2e/test/sts-pvc-unexpected-reboot/assert-csi-driver-resources.yaml
  tests/e2e/test/sts-pvc-unexpected-reboot/assert-sts.yaml
  tests/e2e/test/sts-pvc-unexpected-reboot/chainsaw-test.yaml
  tests/e2e/test/sts-pvc-unexpected-reboot/create-sts.yaml
Labels: testing
